-- GLORON BEAUTY review system
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  rating integer not null check (rating between 1 and 5),
  review_text text not null check (char_length(review_text) between 1 and 800),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Anyone can read approved reviews only.
drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
on public.reviews for select
to anon, authenticated
using (status = 'approved');

-- Anyone can submit a pending review.
-- The browser cannot set an approved status because of this policy.
drop policy if exists "Public can submit pending reviews" on public.reviews;
create policy "Public can submit pending reviews"
on public.reviews for insert
to anon, authenticated
with check (status = 'pending');

-- Do NOT create public UPDATE or DELETE policies.
-- Approve/reject reviews from the Supabase Dashboard as the site owner.

create index if not exists reviews_status_created_at_idx
on public.reviews(status, created_at desc);
